#include <iostream>

#include "pdb_results.h"
#include "pdb_parser.h"
#include "pdb_organizer.h"

// ============================================================================
int main(int argv, char *argc[]) {
  if (argv != 2) {
    std::cerr
        << "Usage: ./analyze_pdb_dump <path-to-pdb-dump-file>\n\tWhere "
           "<path-to-pdb-dump-file> is a file generated by running cvdump.exe, "
           "piping stdout to a dump file."
        << std::endl;
    return EXIT_FAILURE;
  }

  std::string pdb_file(argc[1]);

  PdbParser parser(pdb_file);

  parser.ParseTypeData();

  PdbOrganizer organizer;

  organizer.Organize(parser);

  // auto ci = analyzer.ConstructClassInfo();
  // PdbResults results(ci);

  // std::cout << boost::json::serialize(results.ToJson()) << std::endl;

  return EXIT_SUCCESS;
}
