#include <iostream>

#include "pdb_analyzer.h"
#include "pdb_results.h"

// ============================================================================
int main(int argv, char *argc[]) {
  if (argv != 2) {
    std::cerr
        << "Usage: ./analyze_pdb_dump <path-to-pdb-dump-file>\n\tWhere "
           "<path-to-pdb-dump-file> is a file generated by running cvdump.exe, "
           "piping stdout to a dump file."
        << std::endl;
    return EXIT_FAILURE;
  }

  std::string pdb_file(argc[1]);

  // Analyze PDB dump
  PdbAnalyzer analyzer;
  analyzer.AnalyzePdbDump(pdb_file);

  PdbResults results(analyzer.get_class_info(), analyzer.get_method_list());
  // results.CombineClasses();

  std::cout << boost::json::serialize(results.ToJson()) << std::endl;

  return EXIT_SUCCESS;
}
